### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by WifiRouterYT** [pollev/bash_progress_bar#1]
I get this; 
progress_bar.sh: 29: progress_bar.sh: Syntax error: "(" unexpected
when I run the program. What did I do wrong?

**Comment by pollev** [comment]
Hello,

It seems I made the mistake of combining the "()" and "function" syntax.
This works properly for the bash version I am using, but this might not be the case for yours.

I will fix this ASAP by removing all "()" syntax and only leaving "function" syntax.

**Comment by pollev** [comment]
@CreeperDude372 
I have updated my script. See if your problem is solved now

**Comment by pollev** [comment]
I have made the functions more POSIX compliant (even though this is clearly a bash script). I will close this ticket as resolved.
