### ISSUE TITLE
Progress bar not working in mosh shell

### ISSUE THREAD

**Issue by Linux123123** [pollev/bash_progress_bar#5]
**Is your feature request related to a problem? Please describe.**
The progress bar doesn't work in **`mosh`**. `Mosh` is a alternative low-latency tty like ssh session. It tries to replicate how it would look in tty. 

**Additional context**
It is something with new lines in it, because the progress bar is there, but it gets covered by the script outputting text.

**Comment by pollev** [comment]
Hey man,

It appears that Mosh implements a very limited set of [ANSI control sequences](https://en.wikipedia.org/wiki/ANSI_escape_code).
More specifically, they do not seem to support 

- `CSI s` Save Current Cursor Position
- `CSI u` Restore Saved Cursor Position

Without these two control codes this tool will not work as it relies on them to setup the scrolling area and manage alternating between printing normal output and the progress bar itself.

As a side note: There are potential alternatives to these control codes. But as far as I can tell, it involves grabbing the current location of the cursor through ["suboptimal" means.](https://stackoverflow.com/questions/50884685/how-to-get-cursor-position-in-c-using-ansi-code)
