### ISSUE TITLE
harmonize bar with completed process 

### ISSUE THREAD

**Issue by MostafaYA** [pollev/bash_progress_bar#6]
Hi, thanks for this nice tool. 
How can I stop the progress bar if the primary output file has been created faster than expected?
Best wishes

**Comment by pollev** [comment]
Hi, 

I'm not sure what you mean?

You can easily remove the progress bar by calling 'destroy_scroll_area'.
Does that help?

Kr,
Polle

**Comment by MostafaYA** [comment]
Hi, thanks for your reply. Here is my example 

```
#!/bin/bash

source ./progress_bar.sh

generate_some_output_and_sleep() {
    cp *fastq.gz ./test/
    sleep 0.001
}

main() {
    enable_trapping
    setup_scroll_area
    for i in {1..99}
    do
      generate_some_output_and_sleep
      draw_progress_bar $i
    done
    destroy_scroll_area
}
main
```

In the above example, the process is to copy all data to a folder  ` cp *fastq.gz ./test/`.  All data have been already copied but the progress bar is still running. 
I am looking for a solution which might be that the function `main` be adapted so that if the output files were created in the mean time then do not continue and run `destroy_scroll_area`. Is that possible?

**Comment by pollev** [comment]
Hi,

I am still not fully sure I get what you are trying to do.
If your goal is to use this progress bar to communicate on the progress of file copying, you could for example create a percentage based on the number of files you have copied so far:

```
#!/bin/bash

# Source progress bar
source ./progress_bar.sh


main() {
    # Make sure that the progress bar is cleaned up when user presses ctrl+c
    enable_trapping
    # Create progress bar
    setup_scroll_area
    # Get list of all files in /tmp/test/input that end with "test"
    file_list=$(find "/tmp/test/input/" -type f -name "*test")
    total_nr_files=$(echo "$file_list" | wc -l)
    current_nr=1
    for file in $file_list
    do
        echo "Copying file... $file"
        cp $file /tmp/test/output/
        percentage_complete=$((current_nr*100/total_nr_files))
        draw_progress_bar $percentage_complete
        current_nr=$((current_nr+1))
        sleep 1
    done
    destroy_scroll_area
}

main
```

Is this what you want to do?

**Comment by MostafaYA** [comment]
It worked like a charm - thanks!

**Comment by pollev** [comment]
Keep in mind that this only provides a very basic estimate of the completion percentage. You can improve this a lot more by keeping track of the file sizes of the files you already transferred versus the total size of all the files.

**Comment by pollev** [comment]
Also, of course remove the "sleep" from this example. It is only there for demonstration purposes.
